services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - ./app.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-namesmith_db}
      POSTGRES_USER: ${POSTGRES_USER:-namesmith_admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-replace-with-password}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - namesmith-network

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    volumes:
      - redis-data:/data
    networks:
      - namesmith-network

  api:
    build:
      context: ..
      dockerfile: deploy/api.Dockerfile
    restart: unless-stopped
    env_file:
      - ./app.env
    depends_on:
      - db
      - redis
    expose:
      - "8000"
    networks:
      - namesmith-network

  web:
    build:
      context: ..
      dockerfile: deploy/web.Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    restart: unless-stopped
    env_file:
      - ./app.env
    depends_on:
      - api
    expose:
      - "3000"
    networks:
      - namesmith-network

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template:ro
      - certbot-etc:/etc/letsencrypt:ro
      - certbot-var:/var/lib/letsencrypt:ro
      - certbot-web:/var/www/certbot:ro
    environment:
      DOMAIN: ${DOMAIN:-namesmith.pragnyalabs.com}
    depends_on:
      - api
      - web
    networks:
      - namesmith-network

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - certbot-web:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot --quiet; sleep 12h & wait $${!}; done;'"

volumes:
  postgres-data:
  redis-data:
  certbot-etc:
  certbot-var:
  certbot-web:

networks:
  namesmith-network:
    driver: bridge
